"""Tests for session-first Instagram login in the @beli_eats watcher."""

import base64
import pickle

from beli.eats_watcher import _login_instaloader

PICKLE_SESSION = {"sessionid": "abc123", "csrftoken": "tok", "ds_user_id": "456"}

COOKIES_TXT = """# Netscape HTTP Cookie File
# https://curl.se/docs/http-cookies.html
# This file was generated by Get cookies.txt LOCALLY
.instagram.com\tTRUE\t/\tTRUE\t1999999999\tcsrftoken\ttok
#HttpOnly_.instagram.com\tTRUE\t/\tTRUE\t1999999999\tsessionid\tabc123
.instagram.com\tTRUE\t/\tTRUE\t1999999999\tds_user_id\t456
"""


def _b64(raw: bytes) -> str:
    return base64.b64encode(raw).decode()


class FakeLoader:
    def __init__(self, fail_session: bool = False):
        self.calls = []
        self.fail_session = fail_session

    def load_session(self, username, session_data):
        if self.fail_session:
            raise RuntimeError("session expired")
        assert session_data["sessionid"] == "abc123"
        self.calls.append(("load_session", username))

    def login(self, username, password):
        self.calls.append(("login", username, password))


def test_pickle_session_login_preferred(monkeypatch):
    monkeypatch.setenv("BELI_EATS_IG_SESSION", _b64(pickle.dumps(PICKLE_SESSION)))
    loader = FakeLoader()
    _login_instaloader(loader, "burner", "pw")
    assert loader.calls == [("load_session", "burner")]


def test_cookies_txt_session_login_preferred(monkeypatch):
    monkeypatch.setenv("BELI_EATS_IG_SESSION", _b64(COOKIES_TXT.encode()))
    loader = FakeLoader()
    _login_instaloader(loader, "burner", "pw")
    assert loader.calls == [("load_session", "burner")]


def test_password_fallback_when_no_session(monkeypatch):
    monkeypatch.delenv("BELI_EATS_IG_SESSION", raising=False)
    loader = FakeLoader()
    _login_instaloader(loader, "burner", "pw")
    assert loader.calls == [("login", "burner", "pw")]


def test_password_fallback_when_session_corrupt(monkeypatch):
    monkeypatch.setenv("BELI_EATS_IG_SESSION", "not-valid-base64!!!")
    loader = FakeLoader()
    _login_instaloader(loader, "burner", "pw")
    assert loader.calls == [("login", "burner", "pw")]


def test_password_fallback_when_session_rejected(monkeypatch):
    monkeypatch.setenv("BELI_EATS_IG_SESSION", _b64(pickle.dumps(PICKLE_SESSION)))
    loader = FakeLoader(fail_session=True)
    _login_instaloader(loader, "burner", "pw")
    assert loader.calls == [("login", "burner", "pw")]


def test_password_fallback_when_cookies_txt_has_no_sessionid(monkeypatch):
    monkeypatch.setenv("BELI_EATS_IG_SESSION", _b64(b"some random text"))
    loader = FakeLoader()
    _login_instaloader(loader, "burner", "pw")
    assert loader.calls == [("login", "burner", "pw")]


def test_no_login_without_credentials(monkeypatch):
    monkeypatch.delenv("BELI_EATS_IG_SESSION", raising=False)
    loader = FakeLoader()
    _login_instaloader(loader, None, None)
    assert loader.calls == []
