-- Shared Cozy Commons scene state. The API is the only writer; the browser
-- never receives direct table or RPC access.

create table public.commons_scenes (
  id text primary key,
  layout_version integer not null default 1 check (layout_version > 0),
  version integer not null default 0 check (version >= 0),
  state jsonb not null check (jsonb_typeof(state) = 'object'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.commons_scene_commands (
  id bigint generated by default as identity primary key,
  scene_id text not null references public.commons_scenes(id) on delete cascade,
  actor_key text not null check (char_length(actor_key) between 1 and 128),
  client_command_id text not null check (char_length(client_command_id) between 1 and 128),
  expected_version integer not null check (expected_version >= 0),
  accepted_version integer not null check (accepted_version > 0),
  canonical_payload jsonb not null check (jsonb_typeof(canonical_payload) = 'object'),
  resulting_state jsonb not null check (jsonb_typeof(resulting_state) = 'object'),
  created_at timestamptz not null default now(),
  unique (scene_id, actor_key, client_command_id)
);

create index commons_scene_commands_version_idx
  on public.commons_scene_commands (scene_id, accepted_version);

grant usage, select on sequence public.commons_scene_commands_id_seq to service_role;

alter table public.commons_scenes enable row level security;
alter table public.commons_scene_commands enable row level security;

revoke all on table public.commons_scenes from public, anon, authenticated;
revoke all on table public.commons_scene_commands from public, anon, authenticated;

insert into public.commons_scenes (id, layout_version, version, state)
values (
  'commons-home',
  1,
  0,
  '{
    "schema_version": 1,
    "objects": {
      "record-player": {
        "id": "record-player",
        "kind": "prop",
        "x": 0.285,
        "y": 0.418,
        "movable": true,
        "state": {"playing": false}
      },
      "floor-lamp": {
        "id": "floor-lamp",
        "kind": "prop",
        "x": 0.545,
        "y": 0.725,
        "movable": true,
        "state": {"on": true}
      }
    },
    "actors": {
      "host": {
        "id": "host",
        "kind": "actor",
        "x": 0.555,
        "y": 0.595,
        "facing": "south"
      }
    }
  }'::jsonb
);

create or replace function public.commons_apply_command(
  p_scene_id text,
  p_actor_key text,
  p_client_command_id text,
  p_expected_version integer,
  p_canonical_payload jsonb,
  p_resulting_state jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_scene public.commons_scenes%rowtype;
  v_existing public.commons_scene_commands%rowtype;
  v_new_version integer;
begin
  if coalesce(
    nullif(pg_catalog.current_setting('request.jwt.claims', true), '')::jsonb ->> 'role',
    ''
  ) <> 'service_role' then
    return pg_catalog.jsonb_build_object(
      'ok', false,
      'error_code', 'service_role_required'
    );
  end if;

  select * into v_scene
    from public.commons_scenes
   where id = p_scene_id
   for update;

  if not found then
    return pg_catalog.jsonb_build_object(
      'ok', false,
      'error_code', 'scene_not_found'
    );
  end if;

  -- Check idempotency after taking the scene lock so two simultaneous retries
  -- cannot both pass the read-before-write check.
  select * into v_existing
    from public.commons_scene_commands
   where scene_id = p_scene_id
     and actor_key = p_actor_key
     and client_command_id = p_client_command_id;
  if found then
    if v_existing.canonical_payload = p_canonical_payload then
      return pg_catalog.jsonb_build_object(
        'ok', true,
        'replayed', true,
        'scene_id', p_scene_id,
        'accepted_version', v_existing.accepted_version,
        'version', v_scene.version,
        'client_command_id', p_client_command_id,
        'state', v_scene.state
      );
    end if;
    return pg_catalog.jsonb_build_object(
      'ok', false,
      'error_code', 'command_id_conflict'
    );
  end if;

  if v_scene.version <> p_expected_version then
    return pg_catalog.jsonb_build_object(
      'ok', false,
      'error_code', 'stale_version',
      'current_version', v_scene.version
    );
  end if;

  if pg_catalog.jsonb_typeof(p_canonical_payload) <> 'object'
     or pg_catalog.jsonb_typeof(p_resulting_state) <> 'object'
     or not (p_resulting_state ? 'schema_version')
     or not (p_resulting_state ? 'objects')
     or not (p_resulting_state ? 'actors') then
    return pg_catalog.jsonb_build_object(
      'ok', false,
      'error_code', 'invalid_state'
    );
  end if;

  v_new_version := v_scene.version + 1;

  insert into public.commons_scene_commands (
    scene_id, actor_key, client_command_id, expected_version,
    accepted_version, canonical_payload, resulting_state
  ) values (
    p_scene_id, p_actor_key, p_client_command_id, p_expected_version,
    v_new_version, p_canonical_payload, p_resulting_state
  );

  update public.commons_scenes
     set version = v_new_version,
         state = p_resulting_state,
         updated_at = pg_catalog.now()
   where id = p_scene_id;

  return pg_catalog.jsonb_build_object(
    'ok', true,
    'replayed', false,
    'scene_id', p_scene_id,
    'accepted_version', v_new_version,
    'version', v_new_version,
    'client_command_id', p_client_command_id,
    'state', p_resulting_state
  );
end;
$$;

revoke all on function public.commons_apply_command(text, text, text, integer, jsonb, jsonb)
  from public, anon, authenticated;
grant execute on function public.commons_apply_command(text, text, text, integer, jsonb, jsonb)
  to service_role;
